server:
  port: 9191

spring:
  application:
    name: bmc-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://security-service:8080
          predicates:
            - Path=/login
            - Method=POST
            
        - id: doctor-service
          uri: http://doctor-service:8081
          predicates:
            - Path=/doctors/**
            
        - id: appointment-service
          uri: http://appointment-service:8082
          predicates:
            - Path=/doctor/**,/appointments/**,/users/{userId}/appointments,/prescriptions/**

        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
            
        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/payments/**
            
        - id: rating-service
          uri: http://rating-service:8084
          predicates:
            - Path=/ratings/**